CREATE TABLE type_weaknesses (
    types VARCHAR(50) PRIMARY KEY,
    normal DECIMAL(2, 1),
    fire DECIMAL(2, 1),
    water DECIMAL(2, 1),
    electric DECIMAL(2, 1),
    grass DECIMAL(2, 1),
    ice DECIMAL(2, 1),
    fighting DECIMAL(2, 1),
    poison DECIMAL(2, 1),
    ground DECIMAL(2, 1),
    flying DECIMAL(2, 1),
    psychic DECIMAL(2, 1),
    bug DECIMAL(2, 1),
    rock DECIMAL(2, 1),
    ghost DECIMAL(2, 1),
    dragon DECIMAL(2, 1),
    dark DECIMAL(2, 1),
    steel DECIMAL(2, 1),
    fairy DECIMAL(2, 1)
);

CREATE TABLE base_stats (
    pkmn_name VARCHAR(30) PRIMARY KEY,
    type_1 VARCHAR(10) NOT NULL, 
    type_2 VARCHAR(10), 
    base_hp INTEGER NOT NULL, 
    base_attack INTEGER NOT NULL, 
    base_special_attack INTEGER NOT NULL, 
    base_defense INTEGER NOT NULL, 
    base_special_defense INTEGER NOT NULL, 
    base_speed INTEGER NOT NULL
);

INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('normal', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('fire', 1.0, 0.5, 2.0, 1.0, 0.5, 0.5, 1.0, 1.0, 2.0, 1.0, 1.0, 0.5, 2.0, 1.0, 1.0, 1.0, 0.5, 0.5);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('water', 1.0, 0.5, 0.5, 2.0, 2.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('electric', 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 2.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('grass', 1.0, 2.0, 0.5, 0.5, 0.5, 2.0, 1.0, 2.0, 0.5, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('ice', 1.0, 2.0, 1.0, 1.0, 1.0, 0.5, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 2.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('fighting', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 0.5, 0.5, 1.0, 1.0, 0.5, 1.0, 2.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('poison', 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 0.5, 0.5, 2.0, 1.0, 2.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('ground', 1.0, 1.0, 2.0, 0.0, 2.0, 2.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('flying', 1.0, 1.0, 1.0, 2.0, 0.5, 2.0, 0.5, 1.0, 0.0, 1.0, 1.0, 0.5, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('psychic', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 1.0, 0.5, 2.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('bug', 1.0, 2.0, 1.0, 1.0, 0.5, 1.0, 0.5, 1.0, 0.5, 2.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('rock', 0.5, 0.5, 2.0, 1.0, 2.0, 1.0, 2.0, 0.5, 2.0, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('ghost', 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.5, 1.0, 1.0, 1.0, 0.5, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('dragon', 1.0, 0.5, 0.5, 0.5, 0.5, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('dark', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 0.0, 2.0, 1.0, 0.5, 1.0, 0.5, 1.0, 2.0);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('steel', 0.5, 2.0, 1.0, 1.0, 0.5, 0.5, 2.0, 1.0, 2.0, 0.5, 0.5, 0.5, 0.5, 1.0, 0.5, 1.0, 0.5, 0.5);
INSERT INTO type_weaknesses (types, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy) VALUES ('fairy', 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 2.0, 1.0, 1.0, 1.0, 0.5, 1.0, 1.0, 0.0, 0.5, 2.0, 1.0);


INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bulbasaur, grass, poison, 45, 49, 49, 65, 65, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ivysaur, grass, poison, 60, 62, 63, 80, 80, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (venusaur, grass, poison, 80, 82, 83, 100, 100, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (charmander, fire, NULL, 39, 52, 43, 60, 50, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (charmeleon, fire, NULL, 58, 64, 58, 80, 65, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (charizard, fire, flying, 78, 84, 78, 109, 85, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (squirtle, water, NULL, 44, 48, 65, 50, 64, 43);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wartortle, water, NULL, 59, 63, 80, 65, 80, 58);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (blastoise, water, NULL, 79, 83, 100, 85, 105, 78);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (caterpie, bug, NULL, 45, 30, 35, 20, 20, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (metapod, bug, NULL, 50, 20, 55, 25, 25, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (butterfree, bug, flying, 60, 45, 50, 90, 80, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (weedle, bug, poison, 40, 35, 30, 20, 20, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kakuna, bug, poison, 45, 25, 50, 25, 25, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (beedrill, bug, poison, 65, 90, 40, 45, 80, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pidgey, normal, flying, 40, 45, 40, 35, 35, 56);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pidgeotto, normal, flying, 63, 60, 55, 50, 50, 71);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pidgeot, normal, flying, 83, 80, 75, 70, 70, 101);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rattata, normal, NULL, 30, 56, 35, 25, 35, 72);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (raticate, normal, NULL, 55, 81, 60, 50, 70, 97);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spearow, normal, flying, 40, 60, 30, 31, 31, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (fearow, normal, flying, 65, 90, 65, 61, 61, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ekans, poison, NULL, 35, 60, 44, 40, 54, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (arbok, poison, NULL, 60, 85, 69, 65, 79, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pikachu, electric, NULL, 35, 55, 40, 50, 50, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (raichu, electric, NULL, 60, 90, 55, 90, 80, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sandshrew, ground, NULL, 50, 75, 85, 20, 30, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sandslash, ground, NULL, 75, 100, 110, 45, 55, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidoran-f, poison, NULL, 55, 47, 52, 40, 40, 41);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidorina, poison, NULL, 70, 62, 67, 55, 55, 56);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidoqueen, poison, ground, 90, 92, 87, 75, 85, 76);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidoran-m, poison, NULL, 46, 57, 40, 40, 40, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidorino, poison, NULL, 61, 72, 57, 55, 55, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nidoking, poison, ground, 81, 102, 77, 85, 75, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (clefairy, fairy, NULL, 70, 45, 48, 60, 65, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (clefable, fairy, NULL, 95, 70, 73, 95, 90, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vulpix, fire, NULL, 38, 41, 40, 50, 65, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ninetales, fire, NULL, 73, 76, 75, 81, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (jigglypuff, normal, fairy, 115, 45, 20, 45, 25, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wigglytuff, normal, fairy, 140, 70, 45, 85, 50, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (zubat, poison, flying, 40, 45, 35, 30, 40, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (golbat, poison, flying, 75, 80, 70, 65, 75, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (oddish, grass, poison, 45, 50, 55, 75, 65, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gloom, grass, poison, 60, 65, 70, 85, 75, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vileplume, grass, poison, 75, 80, 85, 110, 90, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (paras, bug, grass, 35, 70, 55, 45, 55, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (parasect, bug, grass, 60, 95, 80, 60, 80, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (venonat, bug, poison, 60, 55, 50, 40, 55, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (venomoth, bug, poison, 70, 65, 60, 90, 75, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (diglett, ground, NULL, 10, 55, 25, 35, 45, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dugtrio, ground, NULL, 35, 80, 50, 50, 70, 120);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (meowth, normal, NULL, 40, 45, 35, 40, 40, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (persian, normal, NULL, 65, 70, 60, 65, 65, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (psyduck, water, NULL, 50, 52, 48, 65, 50, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (golduck, water, NULL, 80, 82, 78, 95, 80, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mankey, fighting, NULL, 40, 80, 35, 35, 45, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (primeape, fighting, NULL, 65, 105, 60, 60, 70, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (growlithe, fire, NULL, 55, 70, 45, 70, 50, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (arcanine, fire, NULL, 90, 110, 80, 100, 80, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (poliwag, water, NULL, 40, 50, 40, 40, 40, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (poliwhirl, water, NULL, 65, 65, 65, 50, 50, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (poliwrath, water, fighting, 90, 95, 95, 70, 90, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (abra, psychic, NULL, 25, 20, 15, 105, 55, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kadabra, psychic, NULL, 40, 35, 30, 120, 70, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (alakazam, psychic, NULL, 55, 50, 45, 135, 95, 120);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (machop, fighting, NULL, 70, 80, 50, 35, 35, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (machoke, fighting, NULL, 80, 100, 70, 50, 60, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (machamp, fighting, NULL, 90, 130, 80, 65, 85, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bellsprout, grass, poison, 50, 75, 35, 70, 30, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (weepinbell, grass, poison, 65, 90, 50, 85, 45, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (victreebel, grass, poison, 80, 105, 65, 100, 70, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tentacool, water, poison, 40, 40, 35, 50, 100, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tentacruel, water, poison, 80, 70, 65, 80, 120, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (geodude, rock, ground, 40, 80, 100, 30, 30, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (graveler, rock, ground, 55, 95, 115, 45, 45, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (golem, rock, ground, 80, 120, 130, 55, 65, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ponyta, fire, NULL, 50, 85, 55, 65, 65, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rapidash, fire, NULL, 65, 100, 70, 80, 80, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slowpoke, water, psychic, 90, 65, 65, 40, 40, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slowbro, water, psychic, 95, 75, 110, 100, 80, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magnemite, electric, steel, 25, 35, 70, 95, 55, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magneton, electric, steel, 50, 60, 95, 120, 70, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (farfetchd, normal, flying, 52, 65, 55, 58, 62, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (doduo, normal, flying, 35, 85, 45, 35, 35, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dodrio, normal, flying, 60, 110, 70, 60, 60, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (seel, water, NULL, 65, 45, 55, 45, 70, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dewgong, water, ice, 90, 70, 80, 70, 95, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (grimer, poison, NULL, 80, 80, 50, 40, 50, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (muk, poison, NULL, 105, 105, 75, 65, 100, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shellder, water, NULL, 30, 65, 100, 45, 25, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cloyster, water, ice, 50, 95, 180, 85, 45, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gastly, ghost, poison, 30, 35, 30, 100, 35, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (haunter, ghost, poison, 45, 50, 45, 115, 55, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gengar, ghost, poison, 60, 65, 60, 130, 75, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (onix, rock, ground, 35, 45, 160, 30, 45, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (drowzee, psychic, NULL, 60, 48, 45, 43, 90, 42);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hypno, psychic, NULL, 85, 73, 70, 73, 115, 67);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (krabby, water, NULL, 30, 105, 90, 25, 25, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kingler, water, NULL, 55, 130, 115, 50, 50, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (voltorb, electric, NULL, 40, 30, 50, 55, 55, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (electrode, electric, NULL, 60, 50, 70, 80, 80, 140);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (exeggcute, grass, psychic, 60, 40, 80, 60, 45, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (exeggutor, grass, psychic, 95, 95, 85, 125, 65, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cubone, ground, NULL, 50, 50, 95, 40, 50, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (marowak, ground, NULL, 60, 80, 110, 50, 80, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hitmonlee, fighting, NULL, 50, 120, 53, 35, 110, 87);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hitmonchan, fighting, NULL, 50, 105, 79, 35, 110, 76);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lickitung, normal, NULL, 90, 55, 75, 60, 75, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (koffing, poison, NULL, 40, 65, 95, 60, 45, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (weezing, poison, NULL, 65, 90, 120, 85, 70, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rhyhorn, ground, rock, 80, 85, 95, 30, 30, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rhydon, ground, rock, 105, 130, 120, 45, 45, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chansey, normal, NULL, 250, 5, 5, 35, 105, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tangela, grass, NULL, 65, 55, 115, 100, 40, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kangaskhan, normal, NULL, 105, 95, 80, 40, 80, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (horsea, water, NULL, 30, 40, 70, 70, 25, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (seadra, water, NULL, 55, 65, 95, 95, 45, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (goldeen, water, NULL, 45, 67, 60, 35, 50, 63);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (seaking, water, NULL, 80, 92, 65, 65, 80, 68);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (staryu, water, NULL, 30, 45, 55, 70, 55, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (starmie, water, psychic, 60, 75, 85, 100, 85, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mr. mime, psychic, fairy, 40, 45, 65, 100, 120, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (scyther, bug, flying, 70, 110, 80, 55, 80, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (jynx, ice, psychic, 65, 50, 35, 115, 95, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (electabuzz, electric, NULL, 65, 83, 57, 95, 85, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magmar, fire, NULL, 65, 95, 57, 100, 85, 93);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pinsir, bug, NULL, 65, 125, 100, 55, 70, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tauros, normal, NULL, 75, 100, 95, 40, 70, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magikarp, water, NULL, 20, 10, 55, 15, 20, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gyarados, water, flying, 95, 125, 79, 60, 100, 81);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lapras, water, ice, 130, 85, 80, 85, 95, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ditto, normal, NULL, 48, 48, 48, 48, 48, 48);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (eevee, normal, NULL, 55, 55, 50, 45, 65, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vaporeon, water, NULL, 130, 65, 60, 110, 95, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (jolteon, electric, NULL, 65, 65, 60, 110, 95, 130);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (flareon, fire, NULL, 65, 130, 60, 95, 110, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (porygon, normal, NULL, 65, 60, 70, 85, 75, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (omanyte, rock, water, 35, 40, 100, 90, 55, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (omastar, rock, water, 70, 60, 125, 115, 70, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kabuto, rock, water, 30, 80, 90, 55, 45, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kabutops, rock, water, 60, 115, 105, 65, 70, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (aerodactyl, rock, flying, 80, 105, 65, 60, 75, 130);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (snorlax, normal, NULL, 160, 110, 65, 65, 110, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (articuno, ice, flying, 90, 85, 100, 95, 125, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (zapdos, electric, flying, 90, 90, 85, 125, 90, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (moltres, fire, flying, 90, 100, 90, 125, 85, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dratini, dragon, NULL, 41, 64, 45, 50, 50, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dragonair, dragon, NULL, 61, 84, 65, 70, 70, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dragonite, dragon, flying, 91, 134, 95, 100, 100, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mewtwo, psychic, NULL, 106, 110, 90, 154, 90, 130);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mew, psychic, NULL, 100, 100, 100, 100, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chikorita, grass, NULL, 45, 49, 65, 49, 65, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bayleef, grass, NULL, 60, 62, 80, 63, 80, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cyndaquil, fire, NULL, 39, 52, 43, 60, 50, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (quilava, fire, NULL, 58, 64, 58, 80, 65, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (typhlosion, fire, NULL, 78, 84, 78, 109, 85, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (totodile, water, NULL, 50, 65, 64, 44, 48, 43);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (croconaw, water, NULL, 65, 80, 80, 59, 63, 58);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (feraligatr, water, NULL, 85, 105, 100, 79, 83, 78);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sentret, normal, NULL, 35, 46, 34, 35, 45, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (furret, normal, NULL, 85, 76, 64, 45, 55, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hoothoot, normal, flying, 60, 30, 30, 36, 56, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (noctowl, normal, flying, 100, 50, 50, 76, 96, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ledyba, bug, flying, 40, 20, 30, 40, 80, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ledian, bug, flying, 55, 35, 50, 55, 110, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spinarak, bug, poison, 40, 60, 40, 40, 40, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ariados, bug, poison, 70, 90, 70, 60, 60, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (crobat, poison, flying, 85, 90, 80, 70, 80, 130);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chinchou, water, electric, 75, 38, 38, 56, 56, 67);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lanturn, water, electric, 125, 58, 58, 76, 76, 67);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pichu, electric, NULL, 20, 40, 15, 35, 35, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cleffa, fairy, NULL, 50, 25, 28, 45, 55, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (igglybuff, normal, fairy, 90, 30, 15, 40, 20, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (togepi, fairy, NULL, 35, 20, 65, 40, 65, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (togetic, fairy, flying, 55, 40, 85, 80, 105, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (natu, psychic, flying, 40, 50, 45, 70, 45, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (xatu, psychic, flying, 65, 75, 70, 95, 70, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mareep, electric, NULL, 55, 40, 40, 65, 45, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (flaaffy, electric, NULL, 70, 55, 55, 80, 60, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ampharos, electric, NULL, 90, 75, 85, 115, 90, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bellossom, grass, NULL, 75, 80, 95, 90, 100, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (marill, water, fairy, 70, 20, 50, 20, 50, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (azumarill, water, fairy, 100, 50, 80, 60, 80, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sudowoodo, rock, NULL, 70, 100, 115, 30, 65, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (politoed, water, NULL, 90, 75, 75, 90, 100, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hoppip, grass, flying, 35, 35, 40, 35, 55, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (skiploom, grass, flying, 55, 45, 50, 45, 65, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (jumpluff, grass, flying, 75, 55, 70, 55, 95, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (aipom, normal, NULL, 55, 70, 55, 40, 55, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sunkern, grass, NULL, 30, 30, 30, 30, 30, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sunflora, grass, NULL, 75, 75, 55, 105, 85, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (yanma, bug, flying, 65, 65, 45, 75, 45, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wooper, water, ground, 55, 45, 45, 25, 25, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (quagsire, water, ground, 95, 85, 85, 65, 65, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (espeon, psychic, NULL, 65, 65, 60, 130, 95, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (umbreon, dark, NULL, 95, 65, 110, 60, 130, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (murkrow, dark, flying, 60, 85, 42, 85, 42, 91);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slowking, water, psychic, 95, 75, 80, 100, 110, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (misdreavus, ghost, NULL, 60, 60, 60, 85, 85, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (unown, psychic, NULL, 48, 72, 48, 72, 48, 48);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wobbuffet, psychic, NULL, 190, 33, 58, 33, 58, 33);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (girafarig, normal, psychic, 70, 80, 65, 90, 65, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pineco, bug, NULL, 50, 65, 90, 35, 35, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (forretress, bug, steel, 75, 90, 140, 60, 60, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dunsparce, normal, NULL, 100, 70, 70, 65, 65, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gligar, ground, flying, 65, 75, 105, 35, 65, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (steelix, steel, ground, 75, 85, 200, 55, 65, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (snubbull, fairy, NULL, 60, 80, 50, 40, 40, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (granbull, fairy, NULL, 90, 120, 75, 60, 60, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (qwilfish, water, poison, 65, 95, 75, 55, 55, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (scizor, bug, steel, 70, 130, 100, 55, 80, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shuckle, bug, rock, 20, 10, 230, 10, 230, 5);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (heracross, bug, fighting, 80, 125, 75, 40, 95, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sneasel, dark, ice, 55, 95, 55, 35, 75, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (teddiursa, normal, NULL, 60, 80, 50, 50, 50, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ursaring, normal, NULL, 90, 130, 75, 75, 75, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slugma, fire, NULL, 40, 40, 40, 70, 40, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magcargo, fire, rock, 50, 50, 120, 80, 80, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (swinub, ice, ground, 50, 50, 40, 30, 30, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (piloswine, ice, ground, 100, 100, 80, 60, 60, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (corsola, water, rock, 55, 55, 85, 65, 85, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (remoraid, water, NULL, 35, 65, 35, 65, 35, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (octillery, water, NULL, 75, 105, 75, 105, 75, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (delibird, ice, flying, 45, 55, 45, 65, 45, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mantine, water, flying, 65, 40, 70, 80, 140, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (skarmory, steel, flying, 65, 80, 140, 40, 70, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (houndour, dark, fire, 45, 60, 30, 80, 50, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (houndoom, dark, fire, 75, 90, 50, 110, 80, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kingdra, water, dragon, 75, 95, 95, 95, 95, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (phanpy, ground, NULL, 90, 60, 60, 40, 40, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (donphan, ground, NULL, 90, 120, 120, 60, 60, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (porygon2, normal, NULL, 85, 80, 90, 105, 95, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (stantler, normal, NULL, 73, 95, 62, 85, 65, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (smeargle, normal, NULL, 55, 20, 35, 20, 45, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tyrogue, fighting, NULL, 35, 35, 35, 35, 35, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hitmontop, fighting, NULL, 50, 95, 95, 35, 110, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (smoochum, ice, psychic, 45, 30, 15, 85, 65, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (elekid, electric, NULL, 45, 63, 37, 65, 55, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magby, fire, NULL, 45, 75, 37, 70, 55, 83);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (miltank, normal, NULL, 95, 80, 105, 40, 70, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (blissey, normal, NULL, 255, 10, 10, 75, 135, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (raikou, electric, NULL, 90, 85, 75, 115, 100, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (entei, fire, NULL, 115, 115, 85, 90, 75, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (suicune, water, NULL, 100, 75, 115, 90, 115, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (larvitar, rock, ground, 50, 64, 50, 45, 50, 41);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pupitar, rock, ground, 70, 84, 70, 65, 70, 51);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tyranitar, rock, dark, 100, 134, 110, 95, 100, 61);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lugia, psychic, flying, 106, 90, 130, 90, 154, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ho-oh, fire, flying, 106, 130, 90, 110, 154, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (celebi, psychic, grass, 100, 100, 100, 100, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (treecko, grass, NULL, 40, 45, 35, 65, 55, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (grovyle, grass, NULL, 50, 65, 45, 85, 65, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sceptile, grass, NULL, 70, 85, 65, 105, 85, 120);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (torchic, fire, NULL, 45, 60, 40, 70, 50, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (combusken, fire, fighting, 60, 85, 60, 85, 60, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (blaziken, fire, fighting, 80, 120, 70, 110, 70, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mudkip, water, NULL, 50, 70, 50, 50, 50, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (marshtomp, water, ground, 70, 85, 70, 60, 70, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (swampert, water, ground, 100, 110, 90, 85, 90, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (poochyena, dark, NULL, 35, 55, 35, 30, 30, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mightyena, dark, NULL, 70, 90, 70, 60, 60, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (zigzagoon, normal, NULL, 38, 30, 41, 30, 41, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (linoone, normal, NULL, 78, 70, 61, 50, 61, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wurmple, bug, NULL, 45, 45, 35, 20, 30, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (silcoon, bug, NULL, 50, 35, 55, 25, 25, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (beautifly, bug, flying, 60, 70, 50, 100, 50, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cascoon, bug, NULL, 50, 35, 55, 25, 25, 15);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dustox, bug, poison, 60, 50, 70, 50, 90, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lotad, water, grass, 40, 30, 30, 40, 50, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lombre, water, grass, 60, 50, 50, 60, 70, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ludicolo, water, grass, 80, 70, 70, 90, 100, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (seedot, grass, NULL, 40, 40, 50, 30, 30, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nuzleaf, grass, dark, 70, 70, 40, 60, 40, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shiftry, grass, dark, 90, 100, 60, 90, 60, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (taillow, normal, flying, 40, 55, 30, 30, 30, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (swellow, normal, flying, 60, 85, 60, 50, 50, 125);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wingull, water, flying, 40, 30, 30, 55, 30, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pelipper, water, flying, 60, 50, 100, 85, 70, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ralts, psychic, fairy, 28, 25, 25, 45, 35, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kirlia, psychic, fairy, 38, 35, 35, 65, 55, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gardevoir, psychic, fairy, 68, 65, 65, 125, 115, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (surskit, bug, water, 40, 30, 32, 50, 52, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (masquerain, bug, flying, 70, 60, 62, 80, 82, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shroomish, grass, NULL, 60, 40, 60, 40, 60, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (breloom, grass, fighting, 60, 130, 80, 60, 60, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slakoth, normal, NULL, 60, 60, 60, 35, 35, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vigoroth, normal, NULL, 80, 80, 80, 55, 55, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (slaking, normal, NULL, 150, 160, 100, 95, 65, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nincada, bug, ground, 31, 45, 90, 30, 30, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ninjask, bug, flying, 61, 90, 45, 50, 50, 160);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shedinja, bug, ghost, 1, 90, 45, 30, 30, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (whismur, normal, NULL, 64, 51, 23, 51, 23, 28);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (loudred, normal, NULL, 84, 71, 43, 71, 43, 48);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (exploud, normal, NULL, 104, 91, 63, 91, 73, 68);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (makuhita, fighting, NULL, 72, 60, 30, 20, 30, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hariyama, fighting, NULL, 144, 120, 60, 40, 60, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (azurill, normal, fairy, 50, 20, 40, 20, 40, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (nosepass, rock, NULL, 30, 45, 135, 45, 90, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (skitty, normal, NULL, 50, 45, 45, 35, 35, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (delcatty, normal, NULL, 70, 65, 65, 55, 55, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sableye, dark, ghost, 50, 75, 75, 65, 65, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mawile, steel, fairy, 50, 85, 85, 55, 55, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (aron, steel, rock, 50, 70, 100, 40, 40, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lairon, steel, rock, 60, 90, 140, 50, 50, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (aggron, steel, rock, 70, 110, 180, 60, 60, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (meditite, fighting, psychic, 30, 40, 55, 40, 55, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (medicham, fighting, psychic, 60, 60, 75, 60, 75, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (electrike, electric, NULL, 40, 45, 40, 65, 40, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (manectric, electric, NULL, 70, 75, 60, 105, 60, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (plusle, electric, NULL, 60, 50, 40, 85, 75, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (minun, electric, NULL, 60, 40, 50, 75, 85, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (volbeat, bug, NULL, 65, 73, 55, 47, 75, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (illumise, bug, NULL, 65, 47, 55, 73, 75, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (roselia, grass, poison, 50, 60, 45, 100, 80, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gulpin, poison, NULL, 70, 43, 53, 43, 53, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (swalot, poison, NULL, 100, 73, 83, 73, 83, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (carvanha, water, dark, 45, 90, 20, 65, 20, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sharpedo, water, dark, 70, 120, 40, 95, 40, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wailmer, water, NULL, 130, 70, 35, 70, 35, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wailord, water, NULL, 170, 90, 45, 90, 45, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (numel, fire, ground, 60, 60, 40, 65, 45, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (camerupt, fire, ground, 70, 100, 70, 105, 75, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (torkoal, fire, NULL, 70, 85, 140, 85, 70, 20);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spoink, psychic, NULL, 60, 25, 35, 70, 80, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (grumpig, psychic, NULL, 80, 45, 65, 90, 110, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spinda, normal, NULL, 60, 60, 60, 60, 60, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (trapinch, ground, NULL, 45, 100, 45, 45, 45, 10);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vibrava, ground, dragon, 50, 70, 50, 50, 50, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (flygon, ground, dragon, 80, 100, 80, 80, 80, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cacnea, grass, NULL, 50, 85, 40, 85, 40, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cacturne, grass, dark, 70, 115, 60, 115, 60, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (swablu, normal, flying, 45, 40, 60, 40, 75, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (altaria, dragon, flying, 75, 70, 90, 70, 105, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (zangoose, normal, NULL, 73, 115, 60, 60, 60, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (seviper, poison, NULL, 73, 100, 60, 100, 60, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lunatone, rock, psychic, 70, 55, 65, 95, 85, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (solrock, rock, psychic, 70, 95, 85, 55, 65, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (barboach, water, ground, 50, 48, 43, 46, 41, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (whiscash, water, ground, 110, 78, 73, 76, 71, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (corphish, water, NULL, 43, 80, 65, 50, 35, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (crawdaunt, water, dark, 63, 120, 85, 90, 55, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (baltoy, ground, psychic, 40, 40, 55, 40, 70, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (claydol, ground, psychic, 60, 70, 105, 70, 120, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lileep, rock, grass, 66, 41, 77, 61, 87, 23);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cradily, rock, grass, 86, 81, 97, 81, 107, 43);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (anorith, rock, bug, 45, 95, 50, 40, 50, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (armaldo, rock, bug, 75, 125, 100, 70, 80, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (feebas, water, NULL, 20, 15, 20, 10, 55, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (milotic, water, NULL, 95, 60, 79, 100, 125, 81);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (castform, normal, NULL, 70, 70, 70, 70, 70, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kecleon, normal, NULL, 60, 90, 70, 60, 120, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shuppet, ghost, NULL, 44, 75, 35, 63, 33, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (banette, ghost, NULL, 64, 115, 65, 83, 63, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (duskull, ghost, NULL, 20, 40, 90, 30, 90, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dusclops, ghost, NULL, 40, 70, 130, 60, 130, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tropius, grass, flying, 99, 68, 83, 72, 87, 51);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chimecho, psychic, NULL, 65, 50, 70, 95, 80, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (absol, dark, NULL, 65, 130, 60, 75, 60, 75);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wynaut, psychic, NULL, 95, 23, 48, 23, 48, 23);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (snorunt, ice, NULL, 50, 50, 50, 50, 50, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (glalie, ice, NULL, 80, 80, 80, 80, 80, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spheal, ice, water, 70, 40, 50, 55, 50, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (sealeo, ice, water, 90, 60, 70, 75, 70, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (walrein, ice, water, 110, 80, 90, 95, 90, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (clamperl, water, NULL, 35, 64, 85, 74, 55, 32);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (huntail, water, NULL, 55, 104, 105, 94, 75, 52);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gorebyss, water, NULL, 55, 84, 105, 114, 75, 52);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (relicanth, water, rock, 100, 90, 130, 45, 65, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (luvdisc, water, NULL, 43, 30, 55, 40, 65, 97);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bagon, dragon, NULL, 45, 75, 60, 40, 30, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shelgon, dragon, NULL, 65, 95, 100, 60, 50, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (salamence, dragon, flying, 95, 135, 80, 110, 80, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (beldum, steel, psychic, 40, 55, 80, 35, 60, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (metang, steel, psychic, 60, 75, 100, 55, 80, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (metagross, steel, psychic, 80, 135, 130, 95, 90, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (regirock, rock, NULL, 80, 100, 200, 50, 100, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (regice, ice, NULL, 80, 50, 100, 100, 200, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (registeel, steel, NULL, 80, 75, 150, 75, 150, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (latias, dragon, psychic, 80, 80, 90, 110, 130, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (latios, dragon, psychic, 80, 90, 80, 130, 110, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kyogre, water, NULL, 100, 100, 90, 150, 140, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (groudon, ground, NULL, 100, 150, 140, 100, 90, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rayquaza, dragon, flying, 105, 150, 90, 150, 90, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (jirachi, steel, psychic, 100, 100, 100, 100, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (deoxys-n, psychic, NULL, 50, 150, 50, 150, 50, 150);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (deoxys-a, psychic, NULL, 50, 180, 20, 180, 20, 150);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (deoxys-d, psychic, NULL, 50, 70, 160, 70, 160, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (deoxys-s, psychic, NULL, 50, 95, 90, 95, 90, 180);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (turtwig, grass, NULL, 55, 68, 64, 45, 55, 31);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (grotle, grass, NULL, 75, 89, 85, 55, 65, 36);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (torterra, grass, ground, 95, 109, 105, 75, 85, 56);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chimchar, fire, NULL, 44, 58, 44, 58, 44, 61);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (monferno, fire, fighting, 64, 78, 52, 78, 52, 81);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (infernape, fire, fighting, 76, 104, 71, 104, 71, 108);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (piplup, water, NULL, 53, 51, 53, 61, 56, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (prinplup, water, NULL, 64, 66, 68, 81, 76, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (empoleon, water, steel, 84, 86, 88, 111, 101, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (starly, normal, flying, 40, 55, 30, 30, 30, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (staravia, normal, flying, 55, 75, 50, 40, 40, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (staraptor, normal, flying, 85, 120, 70, 50, 60, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bidoof, normal, NULL, 59, 45, 40, 35, 40, 31);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bibarel, normal, water, 79, 85, 60, 55, 60, 71);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kricketot, bug, NULL, 37, 25, 41, 25, 41, 25);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (kricketune, bug, NULL, 77, 85, 51, 55, 51, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shinx, electric, NULL, 45, 65, 34, 40, 34, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (luxio, electric, NULL, 60, 85, 49, 60, 49, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (luxray, electric, NULL, 80, 120, 79, 95, 79, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (budew, grass, poison, 40, 30, 35, 50, 70, 55);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (roserade, grass, poison, 60, 70, 65, 125, 105, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cranidos, rock, NULL, 67, 125, 40, 30, 30, 58);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rampardos, rock, NULL, 97, 165, 60, 65, 50, 58);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shieldon, rock, steel, 30, 42, 118, 42, 88, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bastiodon, rock, steel, 60, 52, 168, 47, 138, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (burmy, bug, NULL, 40, 29, 45, 29, 45, 36);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wormadam-p, bug, grass, 60, 59, 85, 79, 105, 36);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wormadam-s, bug, ground, 60, 79, 105, 59, 85, 36);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (wormadam-t, bug, steel, 60, 69, 95, 69, 95, 36);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mothim, bug, flying, 70, 94, 50, 94, 50, 66);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (combee, bug, flying, 30, 30, 42, 30, 42, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (vespiquen, bug, flying, 70, 80, 102, 80, 102, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (pachirisu, electric, NULL, 60, 45, 70, 45, 90, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (buizel, water, NULL, 55, 65, 35, 60, 30, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (floatzel, water, NULL, 85, 105, 55, 85, 50, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cherubi, grass, NULL, 45, 35, 45, 62, 53, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cherrim, grass, NULL, 70, 60, 70, 87, 78, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shellos, water, NULL, 76, 48, 48, 57, 62, 34);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gastrodon, water, ground, 111, 83, 68, 92, 82, 39);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (ambipom, normal, NULL, 75, 100, 66, 60, 66, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (drifloon, ghost, flying, 90, 50, 34, 60, 44, 70);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (drifblim, ghost, flying, 150, 80, 44, 90, 54, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (buneary, normal, NULL, 55, 66, 44, 44, 56, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lopunny, normal, NULL, 65, 76, 84, 54, 96, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mismagius, ghost, NULL, 60, 60, 60, 105, 105, 105);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (honchkrow, dark, flying, 100, 125, 52, 105, 52, 71);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (glameow, normal, NULL, 49, 55, 42, 42, 37, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (purugly, normal, NULL, 71, 82, 64, 64, 59, 112);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chingling, psychic, NULL, 45, 30, 50, 65, 50, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (stunky, poison, dark, 63, 63, 47, 41, 41, 74);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (skuntank, poison, dark, 103, 93, 67, 71, 61, 84);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bronzor, steel, psychic, 57, 24, 86, 24, 86, 23);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bronzong, steel, psychic, 67, 89, 116, 79, 116, 33);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (bonsly, rock, NULL, 50, 80, 95, 10, 45, 10);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mime jr., psychic, fairy, 20, 25, 45, 70, 90, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (happiny, normal, NULL, 100, 5, 5, 15, 65, 30);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (chatot, normal, flying, 76, 65, 45, 92, 42, 91);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (spiritomb, ghost, dark, 50, 92, 108, 92, 108, 35);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gible, dragon, ground, 58, 70, 45, 40, 45, 42);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gabite, dragon, ground, 68, 90, 65, 50, 55, 82);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (garchomp, dragon, ground, 108, 130, 95, 80, 85, 102);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (munchlax, normal, NULL, 135, 85, 40, 40, 85, 5);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (riolu, fighting, NULL, 40, 70, 40, 35, 40, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lucario, fighting, steel, 70, 110, 70, 115, 70, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hippopotas, ground, NULL, 68, 72, 78, 38, 42, 32);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (hippowdon, ground, NULL, 108, 112, 118, 68, 72, 47);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (skorupi, poison, bug, 40, 50, 90, 30, 55, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (drapion, poison, dark, 70, 90, 110, 60, 75, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (croagunk, poison, fighting, 48, 61, 40, 61, 40, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (toxicroak, poison, fighting, 83, 106, 65, 86, 65, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (carnivine, grass, NULL, 74, 100, 72, 90, 72, 46);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (finneon, water, NULL, 49, 49, 56, 49, 61, 66);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lumineon, water, NULL, 69, 69, 76, 69, 86, 91);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mantyke, water, flying, 45, 20, 50, 60, 120, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (snover, grass, ice, 60, 62, 50, 62, 60, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (abomasnow, grass, ice, 90, 92, 75, 92, 85, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (weavile, dark, ice, 70, 120, 65, 45, 85, 125);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magnezone, electric, steel, 70, 70, 115, 130, 90, 60);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (lickilicky, normal, NULL, 110, 85, 95, 80, 95, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rhyperior, ground, rock, 115, 140, 130, 55, 55, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (tangrowth, grass, NULL, 100, 100, 125, 110, 50, 50);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (electivire, electric, NULL, 75, 123, 67, 95, 85, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (magmortar, fire, NULL, 75, 95, 67, 125, 95, 83);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (togekiss, fairy, flying, 85, 50, 95, 120, 115, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (leafeon, grass, NULL, 65, 110, 130, 60, 65, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (glaceon, ice, NULL, 65, 60, 110, 130, 95, 65);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gliscor, ground, flying, 75, 95, 125, 45, 75, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mamoswine, ice, ground, 110, 130, 80, 70, 60, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (porygon-z, normal, NULL, 85, 80, 70, 135, 75, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (gallade, psychic, fighting, 68, 125, 65, 65, 115, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (probopass, rock, steel, 60, 55, 145, 75, 150, 40);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dusknoir, ghost, NULL, 45, 100, 135, 65, 135, 45);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (froslass, ice, ghost, 70, 80, 70, 80, 70, 110);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom, electric, ghost, 50, 50, 77, 95, 77, 91);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom-h, electric, fire, 50, 65, 107, 105, 107, 86);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom-w, electric, water, 50, 65, 107, 105, 107, 86);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom-f, electric, ice, 50, 65, 107, 105, 107, 86);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom-s, electric, flying, 50, 65, 107, 105, 107, 86);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (rotom-c, electric, grass, 50, 65, 107, 105, 107, 86);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (uxie, psychic, NULL, 75, 75, 130, 75, 130, 95);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (mesprit, psychic, NULL, 80, 105, 105, 105, 105, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (azelf, psychic, NULL, 75, 125, 70, 125, 70, 115);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (dialga, steel, dragon, 100, 120, 120, 150, 100, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (palkia, water, dragon, 90, 120, 100, 150, 120, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (heatran, fire, steel, 91, 90, 106, 130, 106, 77);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (regigigas, normal, NULL, 110, 160, 110, 80, 110, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (giratina-a, ghost, dragon, 150, 100, 120, 100, 120, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (giratina-o, ghost, dragon, 150, 120, 100, 120, 100, 90);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (cresselia, psychic, NULL, 120, 70, 120, 75, 130, 85);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (phione, water, NULL, 80, 80, 80, 80, 80, 80);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (manaphy, water, NULL, 100, 100, 100, 100, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (darkrai, dark, NULL, 70, 90, 90, 135, 90, 125);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shaymin-l, grass, NULL, 100, 100, 100, 100, 100, 100);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (shaymin-s, grass, flying, 100, 103, 75, 120, 75, 127);
INSERT INTO base_stats (pkmn_name, type_1, type_2, base_hp, base_attack, base_defense, special_attack, special_defense, speed) VALUES (arceus, normal, NULL, 120, 120, 120, 120, 120, 120);